# Generated by Django 6.1.1 on 2026-10-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institutions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teachingassignment",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="staffassignment",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Администратор учреждения"),
                    ("curator", "Куратор"),
                    ("teacher", "Преподаватель"),
                    ("organizer", "Организатор"),
                    ("workshop_teacher", "Преподаватель мастер-класса"),
                ],
                max_length=20,
            ),
        ),
    ]
