# Generated by Django 6.1.1 on 2026-10-03 19:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="documentversion",
            name="structure",
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name="Comparison",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Ожидает"),
                            ("processing", "Обрабатывается"),
                            ("succeeded", "Готово"),
                            ("failed", "Ошибка"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("result", models.JSONField(default=dict)),
                ("error_code", models.CharField(blank=True, max_length=80)),
                (
                    "initiator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "new",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comparisons_to",
                        to="documents.documentversion",
                    ),
                ),
                (
                    "old",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comparisons_from",
                        to="documents.documentversion",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("old", "new"), name="unique_comparison_versions"
                    )
                ],
            },
        ),
    ]
