# Generated by Django 6.1.1 on 2026-10-03 20:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0002_documentversion_structure_comparison"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="documentversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("previous__isnull", False)),
                fields=("previous",),
                name="unique_document_successor",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("previous__isnull", True)),
                fields=("document",),
                name="unique_document_root",
            ),
        ),
    ]
