# Generated by Django 6.1.1 on 2026-10-03 20:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_course_status_enrollment_status_assignment_and_more"),
        ("institutions", "0003_studentmembership_membership_date_order"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="course",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["draft", "published", "archived"])),
                name="course_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursesubmission",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["draft", "submitted", "revision", "accepted"])
                ),
                name="course_submission_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursesubmission",
            constraint=models.UniqueConstraint(
                condition=models.Q(("previous__isnull", False)),
                fields=("previous",),
                name="unique_course_submission_successor",
            ),
        ),
    ]
