"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "development-only-do-not-use-in-production")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1,testserver").split(",")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    "default": {
        "BACKEND": "django.core.mail.backends.console.EmailBackend",
    },
}

INSTALLED_APPS += [
    "rest_framework",
    "drf_spectacular",
    "corsheaders",
    "accounts",
    "institutions",
    "courses",
    "projects",
    "documents",
    "integrations",
    "publications",
    "invitations",
    "scheduling",
    "crm",
    "workshops",
    "common",
]
MIDDLEWARE.insert(1, "corsheaders.middleware.CorsMiddleware")
MIDDLEWARE.insert(2, "whitenoise.middleware.WhiteNoiseMiddleware")
AUTH_USER_MODEL = "accounts.User"
DATABASES = {
    "default": dj_database_url.parse(
        os.getenv("DATABASE_URL", f"sqlite:///{BASE_DIR / 'db.sqlite3'}"),
        conn_max_age=60,
    )
}
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication"
    ],
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {"anon": "30/minute", "user": "120/minute"},
    "EXCEPTION_HANDLER": "common.api.exception_handler",
}
SPECTACULAR_SETTINGS = {
    "TITLE": "Инженеры будущего API",
    "VERSION": "0.1.0",
    "COMPONENT_SPLIT_REQUEST": True,
}
CORS_ALLOWED_ORIGINS = [
    x for x in os.getenv("CORS_ALLOWED_ORIGINS", "").split(",") if x
]
CSRF_TRUSTED_ORIGINS = [
    x for x in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",") if x
]
CORS_ALLOW_CREDENTIALS = True
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_ROOT = BASE_DIR / "media"
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"
    },
}
if os.getenv("S3_BUCKET"):
    STORAGES["default"] = {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "bucket_name": os.environ["S3_BUCKET"],
            "access_key": os.getenv("S3_ACCESS_KEY"),
            "secret_key": os.getenv("S3_SECRET_KEY"),
            "endpoint_url": os.getenv("S3_ENDPOINT_URL"),
            "region_name": os.getenv("S3_REGION", "us-east-1"),
            "default_acl": None,
            "file_overwrite": False,
            "querystring_auth": True,
            "addressing_style": "path",
        },
    }
CELERY_BROKER_URL = os.getenv("REDIS_URL", "redis://localhost:6379/0")
CELERY_TASK_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_IGNORE_RESULT = True
CELERY_TASK_PUBLISH_RETRY = False
CELERY_BROKER_CONNECTION_TIMEOUT = 2
CELERY_BROKER_TRANSPORT_OPTIONS = {"socket_connect_timeout": 2, "socket_timeout": 2}
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": CELERY_BROKER_URL,
    }
}
INVITATION_ENCRYPTION_KEY = os.getenv("INVITATION_ENCRYPTION_KEY", "")
WEB_URL = os.getenv("WEB_URL", "http://localhost:5173")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "platform@localhost")
MAILERS = {
    "default": {
        "BACKEND": "django.core.mail.backends.smtp.EmailBackend",
        "OPTIONS": {
            "host": os.getenv("EMAIL_HOST", "mailpit"),
            "port": int(os.getenv("EMAIL_PORT", "1025")),
            "username": os.getenv("EMAIL_USERNAME", ""),
            "password": os.getenv("EMAIL_PASSWORD", ""),
            "use_tls": os.getenv("EMAIL_USE_TLS", "false") == "true",
            "timeout": 15,
        },
    }
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {"console": {"class": "logging.StreamHandler"}},
    "root": {"handlers": ["console"], "level": "INFO"},
    "loggers": {
        "django.server": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        }
    },
}
LANGUAGE_CODE = "ru"
DATA_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 2 * 1024 * 1024
CELERY_BEAT_SCHEDULE = {
    "expire-invitations": {
        "task": "invitations.tasks.expire_invitations",
        "schedule": 300.0,
    }
}

SPECTACULAR_SETTINGS["ENUM_NAME_OVERRIDES"] = {
    "LessonStatus": "common.schema_choices.LESSON_STATUS",
    "InvitationStatus": "common.schema_choices.INVITATION_STATUS",
    "RegistrationStatus": "common.schema_choices.REGISTRATION_STATUS",
    "PartnershipStatus": "common.schema_choices.PARTNERSHIP_STATUS",
}

CELERY_BEAT_SCHEDULE["dispatch-outbox"] = {
    "task": "common.tasks.dispatch_outbox",
    "schedule": 30.0,
}

REST_FRAMEWORK["DEFAULT_PAGINATION_CLASS"] = "common.contract.VersionedPagination"
REST_FRAMEWORK["DEFAULT_FILTER_BACKENDS"] = ["common.contract.AllowedFilters"]
SPECTACULAR_SETTINGS["PREPROCESSING_HOOKS"] = ["common.api.schema_v1"]

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN", "")
GITVERSE_TOKEN = os.getenv("GITVERSE_TOKEN", "")
GITHUB_WEBHOOK_SECRET = os.getenv("GITHUB_WEBHOOK_SECRET", "")
GITVERSE_WEBHOOK_SECRET = os.getenv("GITVERSE_WEBHOOK_SECRET", "")
CELERY_BEAT_SCHEDULE["workshop-opening"] = {
    "task": "workshops.tasks.announce_registration_openings",
    "schedule": 60.0,
}

SPECTACULAR_SETTINGS["ENUM_NAME_OVERRIDES"].update(
    {
        "SubmissionResult": ["draft", "submitted", "accepted", "revision"],
        "LearningReviewResult": ["pending", "accepted", "revision"],
        "DecisionResult": ["accepted", "revision"],
    }
)
SPECTACULAR_SETTINGS["ENUM_NAME_OVERRIDES"].update(
    {
        "CourseLifecycle": ["draft", "published", "archived"],
        "PublicationTransition": ["published", "archived"],
        "EnrollmentLifecycle": ["active", "completed", "cancelled"],
        "ProjectLifecycle": [
            "draft",
            "active",
            "submitted",
            "revision",
            "accepted",
            "archived",
        ],
        "MilestoneLifecycle": [
            "planned",
            "active",
            "submitted",
            "revision",
            "accepted",
        ],
        "ComparisonStatus": ["queued", "processing", "succeeded", "failed"],
        "WorkshopTransition": ["cancelled", "completed"],
        "ApplicationLifecycle": [
            "draft",
            "submitted",
            "revision",
            "accepted",
            "rejected",
            "cancelled",
        ],
        "ApplicationDecision": [
            "submitted",
            "revision",
            "accepted",
            "rejected",
            "cancelled",
        ],
    }
)
