# Generated by Django 6.1.1 on 2026-10-03 19:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0002_documentversion_structure_comparison"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="due_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("active", "В работе"),
                    ("submitted", "На проверке"),
                    ("revision", "Доработка"),
                    ("accepted", "Принят"),
                    ("archived", "Архив"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="projectmember",
            name="role",
            field=models.CharField(
                choices=[("member", "Участник"), ("leader", "Лидер")],
                default="member",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="document_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="documents.documentversion",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="previous",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="revisions",
                to="projects.submission",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="criteria",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="submission",
            name="result",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("submitted", "Отправлено"),
                    ("accepted", "Принято"),
                    ("revision", "На доработку"),
                ],
                default="submitted",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("criteria", models.TextField()),
                ("due_at", models.DateTimeField()),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Запланирован"),
                            ("active", "В работе"),
                            ("submitted", "На проверке"),
                            ("revision", "Доработка"),
                            ("accepted", "Принят"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="milestones",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="task",
            name="milestone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to="projects.milestone",
            ),
        ),
        migrations.CreateModel(
            name="ProjectTransition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("previous", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=20)),
                ("feedback", models.TextField(blank=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transitions",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReviewEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "result",
                    models.CharField(
                        choices=[("revision", "Доработка"), ("accepted", "Принято")],
                        max_length=20,
                    ),
                ),
                ("feedback", models.TextField(blank=True)),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_event",
                        to="projects.submission",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
