# Generated by Django 6.1.1 on 2026-10-03 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institutions", "0001_initial"),
        ("workshops", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="groupapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("confirmed", "Подтверждена"),
                    ("waiting", "Ожидает"),
                    ("cancelled", "Отменена"),
                ],
                default="waiting",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="workshop",
            name="cancelled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workshop",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workshop",
            name="leader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="led_workshops",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workshop",
            name="online_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddConstraint(
            model_name="workshop",
            constraint=models.CheckConstraint(
                condition=models.Q(("starts_at__lt", models.F("ends_at"))),
                name="workshop_time_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="workshop",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("registration_opens_at__lt", models.F("registration_closes_at"))
                ),
                name="workshop_registration_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="workshop",
            constraint=models.CheckConstraint(
                condition=models.Q(("capacity__gt", 0)),
                name="workshop_positive_capacity",
            ),
        ),
        migrations.AddConstraint(
            model_name="workshop",
            constraint=models.CheckConstraint(
                condition=models.Q(("min_age__lte", models.F("max_age"))),
                name="workshop_age_order",
            ),
        ),
    ]
