# Generated by Django 6.1.1 on 2026-10-03 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invitations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="issued_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="issued_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Учащийся"),
                    ("teacher", "Преподаватель"),
                    ("curator", "Куратор"),
                    ("admin", "Администратор учреждения"),
                    ("organizer", "Организатор"),
                    ("workshop_teacher", "Преподаватель мастер-класса"),
                ],
                max_length=20,
            ),
        ),
    ]
