# Generated by Django 6.1.1 on 2026-10-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_user_date_of_birth_loginevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="display_name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
