# Generated by Django 6.1.1 on 2026-10-03 19:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_project_due_at_project_status_projectmember_role_and_more"),
        ("publications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="competition",
            name="visibility",
            field=models.CharField(
                choices=[("public", "Все"), ("authenticated", "Участники")],
                default="public",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="publication",
            name="visibility",
            field=models.CharField(
                choices=[("public", "Все"), ("authenticated", "Участники")],
                default="public",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CompetitionApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("submitted", "Отправлена"),
                            ("revision", "Доработка"),
                            ("accepted", "Принята"),
                            ("rejected", "Отклонена"),
                            ("cancelled", "Отменена"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="publications.competition",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ApplicationTransition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("previous", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=20)),
                ("feedback", models.TextField(blank=True)),
                ("snapshot", models.JSONField(default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="history",
                        to="publications.competitionapplication",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="competitionapplication",
            constraint=models.UniqueConstraint(
                fields=("competition", "project"), name="unique_competition_project"
            ),
        ),
    ]
