# Generated by Django 6.1.1 on 2026-10-08 10:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0003_publication_author_publication_lead"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicationImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="publication-images/%Y/%m")),
                ("content_type", models.CharField(max_length=30)),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="images",
                        to="publications.publication",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
