# Generated by Django 6.1.1 on 2026-10-08 11:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0004_publicationimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicationAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="publication-attachments/%Y/%m")),
                ("filename", models.CharField(max_length=200)),
                ("size", models.PositiveIntegerField()),
                ("removed", models.BooleanField(default=False)),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attachments",
                        to="publications.publication",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
